require("dotenv").config();
const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const Product = require("./models/Product");
const Restaurant = require("./models/Restaurant");
const User = require("./models/User");

mongoose
  .connect(process.env.MONGO_URI)
  .then(() => console.log("MongoDB Connected for Seeding ✅"))
  .catch((err) => console.log(err));

// 🏪 20 RESTAURANTS
const restaurants = [
  {
    name: "Burger Paradise",
    description: "Premium burgers with fresh ingredients",
    image: "https://plus.unsplash.com/premium_photo-1683619761468-b06992704398?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YnVyZ2VyfGVufDB8fDB8fHww",
    cuisine: ["Burgers", "Fast Food", "American"],
    rating: 4.7,
    deliveryTime: "20 min",
    deliveryFee: 30,
    minOrderValue: 150,
    address: "Main Street, Downtown",
    phone: "9876543210",
    isPopular: true,
  },
  {
    name: "Pizza Palace",
    description: "Authentic Italian pizzas with wood-fired oven",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=900&auto=format&fit=crop&q=60",
    cuisine: ["Pizza", "Italian", "European"],
    rating: 4.8,
    deliveryTime: "25 min",
    deliveryFee: 40,
    minOrderValue: 200,
    address: "Market Lane, City Center",
    phone: "9876543211",
    isPopular: true,
  },
  {
    name: "Chicken Express",
    description: "Crispy fried and grilled chicken specialties",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cfd330?w=900&auto=format&fit=crop&q=60",
    cuisine: ["Chicken", "Fast Food"],
    rating: 4.6,
    deliveryTime: "15 min",
    deliveryFee: 25,
    minOrderValue: 120,
    address: "Highland Avenue",
    phone: "9876543212",
    isPopular: true,
  },
  {
    name: "Pasta House",
    description: "Homemade pasta dishes with Italian recipes",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=900&auto=format&fit=crop&q=60",
    cuisine: ["Pasta", "Italian", "European"],
    rating: 4.5,
    deliveryTime: "20 min",
    deliveryFee: 35,
    minOrderValue: 180,
    address: "Vila Road",
    phone: "9876543213",
    isPopular: false,
  },
  {
    name: "Cafe Mocha",
    description: "Beverages and light snacks cafe",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGNhZmV8ZW58MHx8MHx8fDA%3D",
    cuisine: ["Drinks", "Cafe", "Snacks"],
    rating: 4.4,
    deliveryTime: "10 min",
    deliveryFee: 20,
    minOrderValue: 100,
    address: "Beach Street",
    phone: "9876543214",
    isPopular: false,
  },
  {
    name: "Veggie Delight",
    description: "Pure vegetarian cuisine with healthy options",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=900&auto=format&fit=crop&q=60",
    cuisine: ["Vegetarian", "Healthy", "Vegan Options"],
    rating: 4.5,
    deliveryTime: "18 min",
    deliveryFee: 30,
    minOrderValue: 140,
    address: "Green Park",
    phone: "9876543215",
    isPopular: false,
  },
  {
    name: "BBQ Barn",
    description: "Smoky BBQ meats and grilled specialties",
    image: "https://plus.unsplash.com/premium_photo-1667443306658-4664947ffa46?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFyYmVxdWV8ZW58MHx8MHx8fDA%3D",
    cuisine: ["BBQ", "Grilled", "American"],
    rating: 4.6,
    deliveryTime: "30 min",
    deliveryFee: 50,
    minOrderValue: 250,
    address: "Riverside Avenue",
    phone: "9876543216",
    isPopular: true,
  },
  {
    name: "Tandoori Kitchen",
    description: "Authentic Indian tandoori specialties",
    image: "https://plus.unsplash.com/premium_photo-1669245207961-0281fd9396eb?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dGFuZG9vcmklMjBjaGlja2VufGVufDB8fDB8fHww",
    cuisine: ["Indian", "Tandoori", "Spicy"],
    rating: 4.7,
    deliveryTime: "25 min",
    deliveryFee: 35,
    minOrderValue: 180,
    address: "Spice Market",
    phone: "9876543217",
    isPopular: true,
  },
  {
    name: "Sandwich Studio",
    description: "Gourmet sandwiches and fresh subs",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=900&auto=format&fit=crop&q=60",
    cuisine: ["Sandwiches", "Subs", "Fast Food"],
    rating: 4.4,
    deliveryTime: "12 min",
    deliveryFee: 25,
    minOrderValue: 120,
    address: "Commerce Street",
    phone: "9876543218",
    isPopular: false,
  },
  {
    name: "Dragon Wok",
    description: "Asian fusion and noodle specialties",
    image: "https://plus.unsplash.com/premium_photo-1664391771710-4f7eb2a4649a?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bm9vZGxlcyUyMGZyaWVkJTIwcmljZXxlbnwwfHwwfHx8MA%3D%3D",
    cuisine: ["Asian", "Chinese", "Noodles"],
    rating: 4.5,
    deliveryTime: "20 min",
    deliveryFee: 30,
    minOrderValue: 160,
    address: "Chinatown Plaza",
    phone: "9876543219",
    isPopular: true,
  },
  {
    name: "Falafel House",
    description: "Mediterranean and Middle Eastern cuisine",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=900&auto=format&fit=crop&q=60",
    cuisine: ["Mediterranean", "Middle Eastern", "Healthy"],
    rating: 4.3,
    deliveryTime: "18 min",
    deliveryFee: 28,
    minOrderValue: 140,
    address: "Exotic Lane",
    phone: "9876543220",
    isPopular: false,
  },
  {
    name: "Taco Town",
    description: "Mexican street food and authentic tacos",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dGFjb3xlbnwwfHwwfHx8MA%3D%3D",
    cuisine: ["Mexican", "Tacos", "Street Food"],
    rating: 4.6,
    deliveryTime: "18 min",
    deliveryFee: 32,
    minOrderValue: 150,
    address: "Latin Quarter",
    phone: "9876543221",
    isPopular: true,
  },
  {
    name: "Sushi Haven",
    description: "Premium Japanese sushi and rolls",
    image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=900&auto=format&fit=crop&q=60",
    cuisine: ["Japanese", "Sushi", "Asian"],
    rating: 4.7,
    deliveryTime: "25 min",
    deliveryFee: 60,
    minOrderValue: 300,
    address: "Waterfront District",
    phone: "9876543222",
    isPopular: true,
  },
  {
    name: "Sweet Tooth Bakery",
    description: "Fresh baked goods and desserts",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=900&auto=format&fit=crop&q=60",
    cuisine: ["Desserts", "Bakery", "Sweets"],
    rating: 4.8,
    deliveryTime: "15 min",
    deliveryFee: 25,
    minOrderValue: 100,
    address: "Baker Street",
    phone: "9876543223",
    isPopular: true,
  },
  {
    name: "Fish & Chips Co",
    description: "Seafood favorites and fish specialties",
    image: "https://images.unsplash.com/photo-1665401015549-712c0dc5ef85?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZmlzaCUyMGZyeXxlbnwwfHwwfHx8MA%3D%3D",
    cuisine: ["Seafood", "Fish", "British"],
    rating: 4.5,
    deliveryTime: "22 min",
    deliveryFee: 40,
    minOrderValue: 200,
    address: "Harbor Street",
    phone: "9876543224",
    isPopular: false,
  },
  {
    name: "Korean BBQ Plus",
    description: "Korean BBQ and kimchi specialties",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=900&auto=format&fit=crop&q=60",
    cuisine: ["Korean", "BBQ", "Asian"],
    rating: 4.6,
    deliveryTime: "25 min",
    deliveryFee: 45,
    minOrderValue: 220,
    address: "Korean Town",
    phone: "9876543225",
    isPopular: true,
  },
  {
    name: "Smoothie Station",
    description: "Fresh smoothies and healthy bowls",
    image: "https://images.unsplash.com/photo-1600718374662-0483d2b9da44?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHNtb290aGllfGVufDB8fDB8fHww",
    cuisine: ["Smoothies", "Healthy", "Breakfast"],
    rating: 4.4,
    deliveryTime: "12 min",
    deliveryFee: 20,
    minOrderValue: 120,
    address: "Wellness Plaza",
    phone: "9876543226",
    isPopular: false,
  },
  {
    name: "Biryani Nights",
    description: "Traditional biryani and rice dishes",
    image: "https://images.unsplash.com/photo-1697155406055-2db32d47ca07?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YmlyeWFuaXxlbnwwfHwwfHx8MA%3D%3D",
    cuisine: ["Indian", "Biryani", "Asian"],
    rating: 4.7,
    deliveryTime: "28 min",
    deliveryFee: 35,
    minOrderValue: 180,
    address: "Spice District",
    phone: "9876543227",
    isPopular: true,
  },
  {
    name: "Grill House",
    description: "Premium grilled steaks and meats",
    image: "https://images.unsplash.com/photo-1592011432621-f7f576f44484?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3JpbGxlZCUyMGNoaWNrZW58ZW58MHx8MHx8fDA%3D",
    cuisine: ["Steaks", "Grilled", "American"],
    rating: 4.8,
    deliveryTime: "30 min",
    deliveryFee: 55,
    minOrderValue: 300,
    address: "Prime District",
    phone: "9876543228",
    isPopular: true,
  },
  {
    name: "Wrap & Roll",
    description: "Fresh wraps and healthy bowls",
    image: "https://images.unsplash.com/photo-1762631383612-ee9366e58431?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHJvbGwlMjBjaGlja2VufGVufDB8fDB8fHww",
    cuisine: ["Wraps", "Healthy", "Vegetarian"],
    rating: 4.5,
    deliveryTime: "15 min",
    deliveryFee: 28,
    minOrderValue: 130,
    address: "Health Street",
    phone: "9876543229",
    isPopular: false,
  }
];

// 🍕 FOOD ITEMS (Now linked to restaurants)
const foods = [
  {
    name: "Cheese Burger",
    price: 120,
    description: "Juicy grilled burger with cheese",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Y2hlZXNlJTIwYnVyZ2VyfGVufDB8fDB8fHww",
    category: "burger",
    isVeg: false,
    spicyLevel: "medium",
    prepTime: "15 min",
    isPopular: true,
    restaurantIndex: 0,
  },
  {
    name: "Double Cheese Burger",
    price: 180,
    description: "Double patty with double cheese",
    image: "https://media.istockphoto.com/id/1347892065/photo/the-ultimate-double-spicy-crispy-fried-chicken-burger.webp?a=1&b=1&s=612x612&w=0&k=20&c=xmPLvNaRd8UUCwHbCt13yG_lyGuegAqR-NoMi2WhOZQ=",
    category: "burger",
    isVeg: false,
    spicyLevel: "high",
    prepTime: "18 min",
    rating: 5,
    isPopular: true,
    restaurantIndex: 0,
  },
  {
    name: "Veg Burger",
    price: 110,
    description: "Crispy veg patty with fresh lettuce and mayo",
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmVnJTIwYnVyZ2VyfGVufDB8fDB8fHww",
    category: "burger",
    isVeg: true,
    spicyLevel: "medium",
    prepTime: "15 min",
    rating: 4,
    isPopular: true,
    restaurantIndex: 0,
  },
  {
    name: "Margherita Pizza",
    price: 250,
    description: "Classic cheese pizza with fresh basil",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fE1hcmdoZXJpdGElMjBQaXp6YXxlbnwwfHwwfHx8MA%3D%3D",
    category: "pizza",
    isVeg: true,
    prepTime: "20 min",
    isRecommended: true,
    restaurantIndex: 1,
  },
  {
    name: "Pepperoni Pizza",
    price: 320,
    description: "Loaded pepperoni with mozzarella cheese",
    image: "https://images.unsplash.com/photo-1670757781705-9b6cb1ad0ca6?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHBlcHBlcm9uaSUyMHBpenphfGVufDB8fDB8fHww",
    category: "pizza",
    isVeg: false,
    spicyLevel: "medium",
    prepTime: "25 min",
    rating: 5,
    isPopular: true,
    restaurantIndex: 1,
  },
  {
    name: "Farmhouse Pizza",
    price: 280,
    description: "Fresh veggies with rich cheese",
    image: "https://plus.unsplash.com/premium_photo-1733306588881-0411931d4fed?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZmFybWhvdXNlJTIwcGl6emF8ZW58MHx8MHx8fDA%3D",
    category: "pizza",
    isVeg: true,
    spicyLevel: "low",
    prepTime: "22 min",
    rating: 4,
    isRecommended: true,
    restaurantIndex: 1,
  },
  {
    name: "BBQ Chicken Pizza",
    price: 350,
    description: "Barbecue chicken with cheese",
    image: "https://images.unsplash.com/photo-1594007654729-407eedc4be65?w=900&auto=format&fit=crop&q=60",
    category: "pizza",
    isVeg: false,
    spicyLevel: "medium",
    prepTime: "25 min",
    rating: 5,
    isPopular: true,
    restaurantIndex: 1,
  },
  {
    name: "Fried Chicken",
    price: 180,
    description: "Crispy fried chicken",
    image: "https://plus.unsplash.com/premium_photo-1683139916670-38113db90cb9?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8RnJpZWQlMjBDaGlja2VufGVufDB8fDB8fHww",
    category: "chicken",
    isVeg: false,
    spicyLevel: "high",
    restaurantIndex: 2,
  },
  {
    name: "Grilled Chicken",
    price: 240,
    description: "Tender grilled chicken breast",
    image: "https://images.unsplash.com/photo-1621790404813-df280c2de418?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGdyaWxsZWQlMjBjaGlja2VufGVufDB8fDB8fHww",
    category: "chicken",
    isVeg: false,
    spicyLevel: "medium",
    prepTime: "25 min",
    rating: 5,
    isRecommended: true,
    restaurantIndex: 2,
  },
  {
    name: "Chicken Wings",
    price: 210,
    description: "Spicy grilled chicken wings",
    image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=900&auto=format&fit=crop&q=60",
    category: "chicken",
    isVeg: false,
    spicyLevel: "high",
    prepTime: "20 min",
    rating: 4,
    isPopular: true,
    restaurantIndex: 2,
  },
  {
    name: "Tandoori Chicken",
    price: 300,
    description: "Authentic spicy tandoori chicken",
    image: "https://plus.unsplash.com/premium_photo-1669245207961-0281fd9396eb?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dGFuZG9vcmklMjBjaGlja2VufGVufDB8fDB8fHww",
    category: "chicken",
    isVeg: false,
    spicyLevel: "high",
    prepTime: "30 min",
    rating: 5,
    isPopular: true,
    restaurantIndex: 7,
  },
  {
    name: "Pasta Alfredo",
    price: 200,
    description: "Creamy white sauce pasta",
    image: "https://images.unsplash.com/photo-1662478838323-2b4d9dba8ce8?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fFBhc3RhJTIwQWxmcmVkb3xlbnwwfHwwfHx8MA%3D%3D",
    category: "pasta",
    isVeg: true,
    restaurantIndex: 3,
  },
  {
    name: "White Sauce Pasta",
    price: 190,
    description: "Creamy white sauce with herbs",
    image: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=900&auto=format&fit=crop&q=60",
    category: "pasta",
    isVeg: true,
    spicyLevel: "low",
    prepTime: "18 min",
    rating: 4,
    restaurantIndex: 3,
  },
  {
    name: "Red Sauce Pasta",
    price: 180,
    description: "Tangy tomato sauce pasta",
    image: "https://images.unsplash.com/photo-1608756687911-aa1599ab3bd9?w=900&auto=format&fit=crop&q=60",
    category: "pasta",
    isVeg: true,
    spicyLevel: "medium",
    prepTime: "18 min",
    rating: 4,
    isPopular: true,
    restaurantIndex: 3,
  },
  {
    name: "Cheese Pasta",
    price: 210,
    description: "Loaded cheesy pasta delight",
    image: "https://images.unsplash.com/photo-1697155406432-29e76141cde6?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y2hlZXNlJTIwcGFzdGF8ZW58MHx8MHx8fDA%3D",
    category: "pasta",
    isVeg: true,
    spicyLevel: "low",
    prepTime: "20 min",
    rating: 5,
    isPopular: true,
    restaurantIndex: 3,
  },
  {
    name: "Cold Coffee",
    price: 90,
    description: "Chilled creamy coffee",
    image: "https://images.unsplash.com/photo-1625242662341-5e92c5101338?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Q29sZCUyMENvZmZlZXxlbnwwfHwwfHx8MA%3D%3D",
    category: "drinks",
    isVeg: true,
    restaurantIndex: 4,
  },
  {
    name: "Chocolate Shake",
    price: 120,
    description: "Rich chocolate milkshake",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=900&auto=format&fit=crop&q=60",
    category: "drinks",
    isVeg: true,
    spicyLevel: "low",
    prepTime: "10 min",
    rating: 5,
    isPopular: true,
    restaurantIndex: 4,
  },
  {
    name: "Strawberry Shake",
    price: 110,
    description: "Fresh strawberry milkshake",
    image: "https://plus.unsplash.com/premium_photo-1695927470038-35a215e794f0?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8c3RyYXdiZXJyeSUyMHNoYWtlfGVufDB8fDB8fHww",
    category: "drinks",
    isVeg: true,
    spicyLevel: "low",
    prepTime: "10 min",
    rating: 4,
    restaurantIndex: 4,
  },
  {
    name: "Mojito",
    price: 100,
    description: "Refreshing mint lime drink",
    image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=900&auto=format&fit=crop&q=60",
    category: "drinks",
    isVeg: true,
    spicyLevel: "low",
    prepTime: "8 min",
    rating: 4,
    isPopular: true,
    restaurantIndex: 4,
  },
  {
    name: "Iced Tea",
    price: 85,
    description: "Chilled lemon iced tea",
    image: "https://images.unsplash.com/photo-1497534446932-c925b458314e?w=900&auto=format&fit=crop&q=60",
    category: "drinks",
    isVeg: true,
    spicyLevel: "low",
    prepTime: "8 min",
    rating: 4,
    restaurantIndex: 4,
  },
  {
    name: "French Fries",
    price: 90,
    description: "Crispy golden fries",
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=900&auto=format&fit=crop&q=60",
    category: "snacks",
    isVeg: true,
    spicyLevel: "low",
    prepTime: "12 min",
    rating: 4,
    isPopular: true,
    restaurantIndex: 0,
  },
  {
    name: "Paneer Tikka",
    price: 220,
    description: "Spicy grilled paneer cubes",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900&auto=format&fit=crop&q=60",
    category: "snacks",
    isVeg: true,
    spicyLevel: "high",
    prepTime: "20 min",
    rating: 5,
    isPopular: true,
    restaurantIndex: 7,
  },
  {
    name: "Garlic Bread",
    price: 120,
    description: "Toasted bread with garlic butter",
    image: "https://images.unsplash.com/photo-1573140401552-3fab0b24306f?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z2FybGljJTIwYnJlYWR8ZW58MHx8MHx8fDA%3D",
    category: "snacks",
    isVeg: true,
    spicyLevel: "low",
    prepTime: "10 min",
    rating: 4,
    restaurantIndex: 1,
  },
  {
    name: "Veg Sandwich",
    price: 80,
    description: "Fresh vegetable sandwich",
    image: "https://plus.unsplash.com/premium_photo-1664472757995-3260cd26e477?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dmVnJTIwc2FuZHdpY2h8ZW58MHx8MHx8fDA%3D",
    category: "sandwich",
    isVeg: true,
    spicyLevel: "low",
    prepTime: "10 min",
    rating: 4,
    restaurantIndex: 8,
  },
  {
    name: "Chicken Sandwich",
    price: 130,
    description: "Grilled chicken sandwich",
    image: "https://plus.unsplash.com/premium_photo-1683655058728-415f4f2674bf?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2hpY2tlbiUyMHNhbmR3aWNofGVufDB8fDB8fHww",
    category: "sandwich",
    isVeg: false,
    spicyLevel: "medium",
    prepTime: "12 min",
    rating: 4,
    isPopular: true,
    restaurantIndex: 8,
  },
  {
    name: "Biryani",
    price: 280,
    description: "Fragrant royal biryani",
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YmlyeWFuaXxlbnwwfHwwfHx8MA%3D%3D",
    category: "rice",
    isVeg: false,
    spicyLevel: "high",
    prepTime: "30 min",
    rating: 5,
    restaurantIndex: 17,
  },
  {
    name: "Veg Biryani",
    price: 220,
    description: "Aromatic vegetable biryani",
    image: "https://images.unsplash.com/photo-1630409346824-4f0e7b080087?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmVnJTIwYmlyeWFuaXxlbnwwfHwwfHx8MA%3D%3D",
    category: "rice",
    isVeg: true,
    spicyLevel: "medium",
    prepTime: "28 min",
    rating: 4,
    restaurantIndex: 17,
  },
];

const seedData = async () => {
  try {
    // Drop the unique index on adminId if it exists
    try {
      await Restaurant.collection.dropIndex("adminId_1");
      console.log("✅ Dropped old unique index on adminId");
    } catch (err) {
      if (err.code === 27) {
        console.log("✅ No index to drop");
      } else {
        console.log("ℹ️  Index drop info:", err.message);
      }
    }

    // Clear existing data
    await Product.deleteMany();
    await Restaurant.deleteMany();
    await User.deleteMany();

    // Create a system admin user for seeding
    const hashedPassword = await bcrypt.hash("admin123", 10);
    const systemAdmin = new User({
      name: "System Admin",
      email: "admin@foodhub.com",
      password: hashedPassword,
      isAdmin: true,
      phone: "9000000000",
    });
    await systemAdmin.save();
    console.log(`✅ System admin created: ${systemAdmin._id}`);

    // Update restaurants with adminId
    const restaurantsWithAdmin = restaurants.map((restaurant) => ({
      ...restaurant,
      adminId: systemAdmin._id,
      isActive: true,
    }));

    // Insert restaurants first
    const insertedRestaurants = await Restaurant.insertMany(restaurantsWithAdmin);
    console.log(`✅ ${insertedRestaurants.length} restaurants inserted`);

    // Update foods with actual restaurant IDs
    const foodsWithRestaurants = foods.map((food) => ({
      ...food,
      restaurant: insertedRestaurants[food.restaurantIndex]._id,
      restaurantId: insertedRestaurants[food.restaurantIndex]._id,
    }));

    // Remove the temporary restaurantIndex field
    foodsWithRestaurants.forEach((food) => delete food.restaurantIndex);

    // Insert foods
    await Product.insertMany(foodsWithRestaurants);
    console.log(`✅ ${foodsWithRestaurants.length} food items inserted`);
    console.log("🍔 Seed data completed successfully!");
    console.log("📧 Default Admin Email: admin@foodhub.com");
    console.log("🔑 Default Admin Password: admin123");
    process.exit();
  } catch (error) {
    console.log("❌ Error:", error.message);
    console.log(error);
    process.exit(1);
  }
};

seedData();